// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_s0GZwryXjqMjlp-jME96IuCnsnpQxec',
    appId: '1:658193986557:web:8e384080423aa208c7df94',
    messagingSenderId: '658193986557',
    projectId: 'my-unique-app-cross-less',
    authDomain: 'my-unique-app-cross-less.firebaseapp.com',
    storageBucket: 'my-unique-app-cross-less.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpTenVXnqZoxugtbRVSd0KrFI3vQUdNSA',
    appId: '1:658193986557:android:33120e217db95874c7df94',
    messagingSenderId: '658193986557',
    projectId: 'my-unique-app-cross-less',
    storageBucket: 'my-unique-app-cross-less.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd_7NRJqZ4pz_Nq3U0exh7BC9K77Z_ar8',
    appId: '1:658193986557:ios:67585f48821111b1c7df94',
    messagingSenderId: '658193986557',
    projectId: 'my-unique-app-cross-less',
    storageBucket: 'my-unique-app-cross-less.appspot.com',
    iosBundleId: 'com.example.breakingBad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd_7NRJqZ4pz_Nq3U0exh7BC9K77Z_ar8',
    appId: '1:658193986557:ios:67585f48821111b1c7df94',
    messagingSenderId: '658193986557',
    projectId: 'my-unique-app-cross-less',
    storageBucket: 'my-unique-app-cross-less.appspot.com',
    iosBundleId: 'com.example.breakingBad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_s0GZwryXjqMjlp-jME96IuCnsnpQxec',
    appId: '1:658193986557:web:3498f65230c87f37c7df94',
    messagingSenderId: '658193986557',
    projectId: 'my-unique-app-cross-less',
    authDomain: 'my-unique-app-cross-less.firebaseapp.com',
    storageBucket: 'my-unique-app-cross-less.appspot.com',
  );
}
